<?php

namespace Test\TwitterBundle\Repository;

/**
 * TweetsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetsRepository extends \Doctrine\ORM\EntityRepository
{
}
